### ISSUE TITLE
Tarea 4: Duda con inicio de endpoints

### ISSUE THREAD

**Issue by alafa** [caseonit/imhapi#27]
Hello personitas,

En la tarea 4, en el apartado ayuda dice que:

> server.start() debe estar dentro del callback de server.register(), de otro modo el servidor se iniciará antes de que se hayan añadido todas las rutas.

Entiendo rutas como endpoints y como plugins. ¿Sí? ¿O son cosas diferentes?

Suponiendo que así sea, ¿Porque hay que iniciar el servidor en el callback de la función que devuelve la versión?

Si la función `register()` de `/lib/version.js`lo que hace es esperar a que alguien haga petición `http://localhost:8000/version` y en el callback devolver el resultado... ¿No es ilógico que se inicie después de esto?

Hay algo que he entendido mal y por eso no me cuadran estas cosas :sweat_smile:

¿Alguien?

**Comment by alafa** [comment]
@danicg :eyes:

**Comment by danicg** [comment]
@alafa La funcion server.register("plugin", ....), lo que hace es registrar el plugin que le indiques en el servidor que estás instanciando. Al ejecutarse node de forma asíncrona si no realizas el server.start() cuando ya se ha realizado la carga de los plugins, cabe la posibilidad de que el servidor se arranque sin tener los plugin cargados y por lo tanto el servidor no tiene registrado el endpoint que has definido en el register del plugin y te devolverá un 404.

**Comment by alafa** [comment]
Ok pero cuando llamas a la función de register en el callback no esperas a que te devuelva la respuesta del endpoint? Y es que si nadie lo ha llamado, no va a haber respuesta. :worried:

**Comment by danicg** [comment]
@alafa el callback del register se lanza cuando se finaliza el registro de los plugins, lo que se lanza cuando alguien accede al /version es el handler definido en el server.route

**Comment by alafa** [comment]
Gracias @danicg !!
