### ISSUE TITLE
if (err) trough err and Hoek.assert()

### ISSUE THREAD

**Issue by alafa** [caseonit/imhapi#31]
En este código:

```
server.start((err) => {

        if (err) {
            throw err;
        }
        Hoek.assert(!err, err);

        console.log('Server running at:', server.info.uri);
    });
```

¿Porque se trata el error dos veces? ¿Es correcto?

**Comment by Miguel-Herrero** [comment]
Si lo hemos dejado así es porque se nos ha escapado. Creo que con `Hoek.assert(!err, err);` es suficiente (si hay un error, salta la excepción)
